project:
  type: book
  output-dir: docs
  
book:
  title: "Wielowymiarowa analiza danych"
  reader-mode: true
  language: setup/polski.yml
  page-footer:
    left: |
      Wielowymiarowa analiza danych
    right: |
      Dariusz Majerek Â©2025
  favicon: images/cover.png
  cover-image: images/cover.png  
  repo-url: https://github.com/DariuszMajerek/WAD_new
  repo-actions: [issue]
  sharing: [twitter]
  search: true
  author: 
  - name: Dariusz Majerek
    affiliation: Politechnika Lubelska
  date: last-modified
  sidebar: 
    logo: images/logo.jpg
  chapters:
    - index.qmd
    - multi_tests.qmd
    - cca.qmd
    - fa.qmd
    - sem.qmd
    - pca.qmd
    - cluster.qmd
    - correspondence.qmd
    - log_linear.qmd
    - references.qmd

bibliography: references.bib
reference-location: margin
lightbox: true

format:
  html:
    grid:
      sidebar-width: 300px
      body-width: 1400px
      margin-width: 300px
      gutter-width: 1.5rem
    lang: pl
    theme:
      light: [flatly, mycss.scss]
      dark: [darkly, mycss.scss]
    code-link: true
    code-fold: show
    fig-align: center
    crossref:
      fig-title: Rys.     
      tbl-title: Tab.     
      fig-prefix: Rys.
      tbl-prefix: Tab.

execute: 
  warning: false

editor: visual

